openapi: 3.0.0
info:
  title: corp-collab-server
  description: 
  version: 1.0.0

servers:
  - url: http://43.202.203.36
    description: Local development server

paths:
  /:
    get:
      summary: Returns a hello message
      responses:
        '200':
          description: A JSON object with a message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello