openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing users
tags:
  - name: Users
    description: API endpoints related to user management

paths:
  /api/signup:
    post:
      tags:
        - Users
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
                username:
                  type: string
                isStudy:
                  type: boolean
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /api/users/{userId}:
    get:
      tags:
        - Users
      summary: Retrieve user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
        '404':
          description: User not found

    put:
      tags:
        - Users
      summary: Update user information
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                isStudy:
                  type: boolean
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found

    delete:
      tags:
        - Users
      summary: Delete user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /api/login:
    post:
      tags:
        - Users
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials
